### ISSUE TITLE
Decay timer should be a countdown

### ISSUE THREAD

**Issue by Richienb** [programical/gitland#84]
At the moment, tiles become unclaimed when their value becomes equal to or above 30. If we are ever to increase this number, all of the bots that assume 30 would break.

The decay timer should instead be a countdown where tiles become unclaimed when their value becomes 0.

**Comment by robsheldon** [comment]
Using a max() function on the entire set of decay values should give bot authors the ceiling value they need, rather than hardcoding it.

I'm not sure it's worth messing about with anyway. Moving towards a tile that's about to decay is almost never the optimal move. I haven't added any code for tile decay to my bot and its behavior hasn't been negatively impacted at all. If anything it's just fallen back to much simpler routefinding logic since more of the map is open at any given time.

**Comment by Richienb** [comment]
@robsheldon The problem with using a `max()` function is that there is a very small chance for an edge case in the order of capturing squares that breaks it. By having it be a countdown, no matter how long the countdown lasts for, ending on 0 would make it dependant code never break.

**Comment by robsheldon** [comment]
>  there is a very small chance for an edge case in the order of capturing squares that breaks it

I don't understand this. Can you explain?

**Comment by Richienb** [comment]
@robsheldon If coordinated correctly, it is possible for the following to happen:

1. All players go idle (or the server/git/GitHub dies) and all of the decaying titles completely decay.
1. Players continue as normal but now the maximum value is 0.

**Comment by robsheldon** [comment]
Hmm. How would this affect bot logic? The first bot to move in this scenario would immediately add the maximum value back to the decay file.

**Comment by SimonMiaou** [comment]
I think in any case, for the bot to work properly, we will need a file that contain the config of the server.
It should contain size of the map, max value before decay and probably more soon.

**Comment by Richienb** [comment]
Map size is easily detectable but the decay time is not. The best strategy is to just count down instead of up.

**Comment by programical** [comment]
Decay timer is now a countdown.
